apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "javacloudtrader.fullname" . }}
  labels:
    app: {{ template "javacloudtrader.name" . }}
    chart: {{ template "javacloudtrader.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "javacloudtrader.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "javacloudtrader.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DBName
              valueFrom:
                configMapKeyRef:
                  name: db2config
                  key: DBName
            - name: DBServer
              valueFrom:
                configMapKeyRef:
                  name: db2config
                  key: DBServer
            - name: DBPort
              valueFrom:
                configMapKeyRef:
                  name: db2config
                  key: DBPort
            - name: DBUsername
              valueFrom:
                secretKeyRef:
                  name: db2secret
                  key: username
            - name: DBPassword
              valueFrom:
                secretKeyRef:
                  name: db2secret
                  key: password
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
